
set(EUREKA_CONFIG_BUILD_DIR ${CMAKE_BINARY_DIR}/inc)
make_directory(${EUREKA_CONFIG_BUILD_DIR})

set(EUREKA_RES_INC_FILE resources.h)
set(EUREKA_RES_CONFIG_FILE ${EUREKA_CONFIG_DIR}/resources.in)

configure_file(${EUREKA_RES_CONFIG_FILE}
	${EUREKA_CONFIG_BUILD_DIR}/${EUREKA_RES_INC_FILE} ) 

set(EUREKA_INC_DIR ${EUREKA_INC_DIR} ${EUREKA_CONFIG_BUILD_DIR})
